Repository beomgye/where-is-my-hometown, pull requests merged in 2023-10, with the labels that each got.

#1 Feat | eslint, prettier, husky, lint-staged, styled-components 세팅
  .eslintrc.json
  .prettierrc
  next.config.js
  package-lock.json
  package.json
  src/pages/_app.jsx
  src/pages/_document.jsx
  src/pages/api/hello.js
  src/pages/index.jsx
  src/styles/Home.module.css
  src/styles/globalStyle.js
  src/styles/globals.css
  src/styles/index.js
  src/styles/theme.js
Labels: enhancement

#16 Feat | Header 컴포넌트 제작
  src/components/common/Header/index.jsx
  src/components/index.js
  src/pages/_document.jsx
Labels: Feat

#18 Feat | OptionContainer 생성 및 관련 Form 추가
  src/components/AssetInputForm/index.js
  src/components/BuildingTypeForm/index.js
  src/components/FinishForm/index.js
  src/components/LocationForm/index.js
  src/components/TradeForm/index.js
  src/components/index.js
  src/containers/OptionContainer/index.jsx
  src/containers/index.js
  src/pages/index.jsx
Labels: Feat

#22 Fix | import/no-extraneous-dependencies 오류 해결
  .eslintrc.json
Labels: bug, Fix

#25 Feat | Form 컴포넌트 레이아웃 제작
  src/components/common/Button/index.jsx
  src/components/common/Form/index.jsx
Labels: Feat, Refactor

#26 Feat | Input 컴포넌트 제작
  src/components/common/Input/index.jsx
  src/components/index.js
Labels: Feat

#27 Feat | Form 컴포넌트 레이아웃 제작 (2)
  src/components/common/Form/index.jsx
Labels: Feat, Designs

#28 Design | RootLayout 수정
  src/pages/_document.jsx
  src/pages/index.jsx
Labels: Designs

#30 Fix | 세미콜론 규칙 추가
  .eslintrc.json
  .prettierrc
Labels: Fix

#31 Feat | AssetInput, Location, Trade 폼 기본 레이아웃 제작
  src/components/AssetInputForm/index.js
  src/components/AssetInputForm/index.jsx
  src/components/LocationForm/index.js
  src/components/LocationForm/index.jsx
  src/components/TradeForm/index.js
  src/components/TradeForm/index.jsx
  src/components/index.js
  src/containers/OptionContainer/index.jsx
Labels: Feat

#33 Design | Form NavBar 추가, CSS 설정
  src/components/common/Form/index.jsx
  src/components/common/NavBar/index.jsx
  src/containers/OptionContainer/index.jsx
  src/pages/_document.jsx
  src/pages/index.jsx
Labels: Refactor, Designs

#35 Feat | 뒤로가기 버튼 기능 구현
  src/components/common/Form/index.jsx
Labels: Feat

#36 Feat | 파일명 변경 및 Form 기본 레이아웃 추가
  src/components/BuildingTypeForm/index.js
  src/components/BuildingTypeForm/index.jsx
  src/components/FinishForm/index.js
  src/components/FinishForm/index.jsx
  src/components/TradeForm/index.jsx
  src/components/common/Header/index.jsx
Labels: Refactor

#37 [Refactor] Form 관련 전체 리팩토링
  next.config.js
  package-lock.json
  src/components/AssetInputForm/index.jsx
  src/components/BuildingTypeForm/index.jsx
  src/components/FinishForm/index.jsx
  src/components/LocationForm/index.jsx
  src/components/TradeForm/index.jsx
  src/components/common/Checkbox/index.jsx
  src/components/common/Form/index.jsx
  src/components/common/Input/index.jsx
  src/components/common/NavBar/index.jsx
  src/components/index.js
  src/containers/OptionContainer/index.jsx
  src/pages/index.jsx
  src/styles/global.js
  src/styles/globalStyle.js
  src/styles/index.js
  src/styles/variables.js
  src/types/plan.js
  src/types/step.js
Labels: Fix, Refactor

#38 [Refactor] Checkbox 관련 문제 발생으로 인한 리팩토링
  src/components/BuildingTypeForm/index.jsx
  src/components/TradeForm/index.jsx
  src/components/common/Checkbox/index.jsx
  src/types/plan.js
Labels: Fix, Refactor

#40 [Refactor] InputField 컴포넌트 리팩토링
  src/components/AssetInputForm/index.jsx
  src/components/common/Input/index.jsx
  src/components/common/InputField/index.jsx
  src/components/index.js
  src/utils/formatMoney.js
Labels: Refactor

#44 [Feat] FinishForm 요약 기능 구현
  src/components/Address/index.jsx
  src/components/BuildingTypeForm/index.jsx
  src/components/FinishForm/index.jsx
  src/components/LocationForm/index.jsx
  src/components/common/Form/index.jsx
  src/components/common/InputField/index.jsx
  src/containers/OptionContainer/index.jsx
Labels: Feat, Refactor

#46 [Feat] Address 불필요한 State 삭제 및 location Form연결
  src/components/Address/index.jsx
  src/components/LocationForm/index.jsx
  src/containers/OptionContainer/index.jsx
Labels: Feat

#49 Refactor | Form Footer 레이아웃 변경
  src/components/common/Form/index.jsx
Labels: Refactor

#50 [Feat] Container 컴포넌트 제작
  src/components/BuildingTypeForm/index.jsx
  src/components/TradeForm/index.jsx
  src/components/common/Container/index.jsx
  src/components/index.js
Labels: Feat, Refactor

#51 [Refactor] Checkbox 로고 변경
  public/icons/checkbox-checked.svg
  public/icons/checkbox-unchecked.svg
  src/components/common/Checkbox/index.jsx
Labels: Refactor

#52 [Fix] react-hook-form ref 오류 해결
  src/components/AssetInputForm/index.jsx
  src/components/common/InputField/index.jsx
Labels: Fix

#53 [Fix] Checkbox react-hook-form ref 오류 해결
  src/components/common/Checkbox/index.jsx
Labels: Fix

#54 [Feat] SplashScreen 컴포넌트 제작 및 구현
  public/icons/vector.svg
  src/components/index.js
  src/components/screens/SplashScreen/index.jsx
  src/pages/index.jsx
Labels: Feat

#55 [Refactor] Assets 입력값 저장 방식 변경
  src/components/common/InputField/index.jsx
  src/components/screens/FinishForm/index.jsx
  src/containers/OptionContainer/index.jsx
Labels: Refactor

#56 [Feat] axios 세팅 및 fetch 구현
  package-lock.json
  package.json
  src/api/axiosInstance.js
  src/containers/OptionContainer/index.jsx
Labels: Feat

#57 Fix | 초기 페이지 렌더링시 FOUC 문제 해결
  src/pages/_document.jsx
Labels: Fix

#60 [Feat] DaumPost API 오류 해결 및 주소입력 창 전체를 눌렀을 떄 클릭 이벤트 추가
  src/components/common/Address/index.jsx
  src/containers/OptionContainer/index.jsx
  src/utils/customStyles.js
Labels: Feat

#62 [Feat & Refactor] navBar 관련 속성 리팩토링 및 hook 제작, 결과값 출력 구현
  src/api/axiosInstance.js
  src/components/common/NavBar/index.jsx
  src/components/screens/AssetInputForm/index.jsx
  src/components/screens/BuildingTypeForm/index.jsx
  src/components/screens/LocationForm/index.jsx
  src/components/screens/SelectInfo/index.jsx
  src/components/screens/SummaryForm/index.jsx
  src/components/screens/TransactionTypeForm/index.jsx
  src/constants/index.js
  src/containers/OptionContainer/index.jsx
  src/hooks/useFindMyHome.jsx
  src/hooks/useStepControl.jsx
  src/types/option.js
  src/types/step.js
Labels: Feat, Refactor

#63 [Feat] Loading 컴포넌트 제작
  next.config.js
  package-lock.json
  package.json
  src/components/common/Loading/index.jsx
  src/components/index.js
  src/containers/OptionContainer/index.jsx
  src/hooks/useFindMyHome.jsx
Labels: Feat

#65 [Refactor] constants 데이터 변수 리팩토링
  src/components/common/NavBar/index.jsx
  src/components/common/Radio/index.jsx
  src/components/screens/AssetInputForm/index.jsx
  src/components/screens/BuildingTypeForm/index.jsx
  src/components/screens/LocationForm/index.jsx
  src/components/screens/SummaryForm/index.jsx
  src/components/screens/TransactionTypeForm/index.jsx
  src/constants/index.js
  src/containers/OptionContainer/index.jsx
  src/hooks/useFindMyHome.jsx
Labels: Refactor

#66 Feat | workflow 환경변수 설정 추가 (.env)
  .github/workflows/deploy.yml
Labels: Depoly

#67 [Deploy] 1차 배포 (2023.10.17 AM 03:59)
  .eslintrc.json
  .github/workflows/deploy.yml
  .gitignore
  .prettierrc
  README.md
  next.config.js
  package-lock.json
  package.json
  public/icons/checkbox-checked.svg
  public/icons/checkbox-unchecked.svg
  public/icons/vector.svg
  src/components/common/Address/index.jsx
  src/components/common/Button/index.jsx
  src/components/common/Container/index.jsx
  src/components/common/Form/index.jsx
  src/components/common/Header/index.jsx
  src/components/common/InputField/index.jsx
  src/components/common/Loading/index.jsx
  src/components/common/NavBar/index.jsx
  src/components/common/Radio/index.jsx
  src/components/index.js
  src/components/screens/AssetInputForm/index.jsx
  src/components/screens/BuildingTypeForm/index.jsx
  src/components/screens/LocationForm/index.jsx
  src/components/screens/SelectInfo/index.jsx
  src/components/screens/SplashScreen/index.jsx
  src/components/screens/SummaryForm/index.jsx
  src/components/screens/TransactionTypeForm/index.jsx
  src/constants/index.js
  src/containers/OptionContainer/index.jsx
  src/containers/index.js
  src/hooks/useFindMyHome.jsx
  src/hooks/useStepControl.jsx
  src/pages/_app.jsx
  src/pages/_document.jsx
  src/pages/api/hello.js
  src/pages/index.jsx
  src/styles/global.js
  src/styles/globalStyle.js
  src/styles/index.js
  src/styles/theme.js
  src/styles/variables.js
  src/utils/customStyles.js
  src/utils/formatMoney.js
Labels: Depoly
